<?php

namespace Database\Seeders;

use App\Models\FugoProvider;
use Illuminate\Database\Seeder;

class FugoProviderSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $games = [
            [
                'name' => 'African Buffalo (50)',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/50',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 23,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'African Buffalo (500)',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/50',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 23,
                'roomId' => 2,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'African Buffalo (5000)',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/50',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 23,
                'roomId' => 3,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'African Buffalo (10000)',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/50',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 23,
                'roomId' => 4,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'African Buffalo Scatter (50)',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/50',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 42,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 1,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'African Buffalo Scatter (500)',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/50',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 42,
                'roomId' => 2,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 1,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fortune Cat',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/FC',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 122,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Autumn Moon',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/AM',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 123,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Golden Century',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/GC',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 124,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Autumn Moon 88',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/am',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 125,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Golden Century 88',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/gc&',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 126,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LuxuryLine Buffalo',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/llb',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 128,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peace LongLife',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/pll',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 134,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Happy Prosperous',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/hp',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 158,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Grand Dragons',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/gd',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 119,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'African Buffalo Megaways',
                'image' => 'https://buffalo-555.s3.ap-southeast-1.amazonaws.com/mg',
                'type' => 'slot',
                'provider' => 'African Buffalo',
                'gameId' => 204,
                'roomId' => 1,
                'jackpot' => 1,
                'rtp' => 95,
                'BuyFreeSpin' => 0,
                'transfer_wallet' => 1,
                'seamless' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        FugoProvider::insert($games);
    }
}
