<?php

namespace Database\Seeders;

use App\Models\Admin\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // $data = [
        //     [
        //         'code' => '1006',
        //         'name' => 'Pragmatic Play',
        //         'short_name' => 'PP',
        //         'order' => 1,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1012',
        //         'name' => 'SBO',
        //         'short_name' => 'SBO',
        //         'order' => 11,
        //         'game_list_status' => '0',
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1013',
        //         'name' => 'Joker',
        //         'short_name' => 'Joker',
        //         'order' => 12,
        //         'status' => 1,

        //     ],
        //     [
        //         'code' => '1016',
        //         'name' => 'YEE Bet',
        //         'short_name' => 'YEE Bet',
        //         'order' => 13,
        //         'game_list_status' => '0',
        //         'status' => 1,

        //     ],
        //     [
        //         'code' => '1020',
        //         'name' => 'WM Casino',
        //         'short_name' => 'WM Casino',
        //         'order' => 14,
        //         'status' => 1,

        //     ],
        //     [
        //         'code' => '1027',
        //         'name' => 'Yggdrasil',
        //         'short_name' => 'Yggdrasil',
        //         'order' => 15,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1034',
        //         'name' => 'Spade Gaming',
        //         'short_name' => 'SG',
        //         'order' => 16,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1035',
        //         'name' => 'Vivo Gaming',
        //         'short_name' => 'VG',
        //         'order' => 17,
        //         'game_list_status' => '0',
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1050',
        //         'name' => 'PlayStar',
        //         'short_name' => 'PlayStar',
        //         'order' => 6,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1056',
        //         'name' => 'TrueLab',
        //         'short_name' => 'TL',
        //         'order' => 18,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1058',
        //         'name' => 'BGaming',
        //         'short_name' => 'BGaming',
        //         'order' => 19,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1060',
        //         'name' => 'Wazdan',
        //         'short_name' => 'Wazdan',
        //         'order' => 20,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1062',
        //         'name' => 'Fazi',
        //         'short_name' => 'FAZI',
        //         'order' => 21,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1063',
        //         'name' => 'Play Pearls',
        //         'short_name' => 'Play Pearls',
        //         'order' => 22,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1064',
        //         'name' => 'Net Game',
        //         'short_name' => 'Net Game',
        //         'order' => 23,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1065',
        //         'name' => 'Kiron',
        //         'short_name' => 'Kiron',
        //         'order' => 24,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1067',
        //         'name' => 'Red Rake',
        //         'short_name' => 'Red Rake',
        //         'order' => 25,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1070',
        //         'name' => 'Boongo',
        //         'short_name' => 'Boongo',
        //         'order' => 26,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1077',
        //         'name' => 'Skywind',
        //         'short_name' => 'SW',
        //         'order' => 29,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1085',
        //         'name' => 'JDB',
        //         'short_name' => 'JDB',
        //         'order' => 4,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1086',
        //         'name' => 'GENESIS',
        //         'short_name' => 'GENESIS',
        //         'order' => 30,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1097',
        //         'name' => 'Funta Gaming',
        //         'short_name' => 'FG',
        //         'order' => 31,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1098',
        //         'name' => 'Felix Gaming',
        //         'short_name' => 'FelixGaming',
        //         'order' => 32,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1101',
        //         'name' => 'ZeusPlay',
        //         'short_name' => 'ZeusPlay',
        //         'order' => 33,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1102',
        //         'name' => 'KA Gaming',
        //         'short_name' => 'KA',
        //         'order' => 7,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1109',
        //         'name' => 'Netent',
        //         'short_name' => 'Netent',
        //         'order' => 34,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1111',
        //         'name' => 'Gaming World',
        //         'short_name' => 'GamingWorld',
        //         'order' => 35,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1001',
        //         'name' => 'Asia Gaming',
        //         'short_name' => 'AsiaGaming',
        //         'order' => 36,
        //         'game_list_status' => '0',
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1002',
        //         'name' => 'Evolution Gaming',
        //         'short_name' => 'EG',
        //         'order' => 37,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1004',
        //         'name' => 'Big Gaming',
        //         'short_name' => 'BG',
        //         'order' => 10,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1007',
        //         'name' => 'PG Soft',
        //         'short_name' => 'PGSoft',
        //         'order' => 2,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1009',
        //         'name' => 'CQ9',
        //         'short_name' => 'CQ9',
        //         'order' => 8,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1022',
        //         'name' => 'Sexy Gaming',
        //         'short_name' => 'SexyGaming',
        //         'order' => 38,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1023',
        //         'name' => 'Real Time Gaming',
        //         'short_name' => 'RealTimeGaming',
        //         'order' => 39,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1091',
        //         'name' => 'Jili',
        //         'short_name' => 'JILI',
        //         'order' => 3,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1038',
        //         'name' => 'King 855',
        //         'short_name' => 'K855',
        //         'order' => 40,
        //         'game_list_status' => '0',
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1041',
        //         'name' => 'Habanero',
        //         'short_name' => 'Habanero',
        //         'order' => 41,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1150',
        //         'name' => 'Live22SM',
        //         'short_name' => 'Live22',
        //         'order' => 42,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1132',
        //         'name' => 'YesGetRich',
        //         'short_name' => 'YesgetRich',
        //         'order' => 43,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1089',
        //         'name' => 'Simple Play	',
        //         'short_name' => 'SP',
        //         'order' => 44,
        //         'game_list_status' => '0',
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1084',
        //         'name' => 'Advant Play',
        //         'short_name' => 'AP',
        //         'order' => 45,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1104',
        //         'name' => 'SSports',
        //         'short_name' => 'Sport',
        //         'order' => 46,
        //         'game_list_status' => '0',
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1055',
        //         'name' => 'Mr Slotty',
        //         'short_name' => 'MrSlotty',
        //         'order' => 48,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1110',
        //         'name' => 'Red Tiger',
        //         'short_name' => 'RedTiger',
        //         'order' => 50,
        //         'status' => 0,
        //     ],
        //     [
        //         'code' => '1100',
        //         'name' => 'SmartSoft',
        //         'short_name' => 'SmartSoft',
        //         'order' => 9,
        //         'status' => 1,
        //     ],

        //     [
        //         'code' => '1110',
        //         'name' => 'Red Tiger',
        //         'short_name' => 'RTiger',
        //         'order' => 50,
        //         'status' => 1,
        //     ],
        //     [
        //         'code' => '1002',
        //         'name' => 'Evolution Gaming',
        //         'short_name' => 'Evolution',
        //         'order' => 51,
        //         'status' => 1,
        //     ],
        // ];
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('products')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        // $data = [
        //     [
        //                    'code' => '1002',
        //                    'name' => 'Evolution Gaming',
        //                    'short_name' => 'EG',
        //                    'order' => 37,
        //                    'status' => 1,
        //                ],
        //                [
        //                    'code' => '1004',
        //                    'name' => 'Big Gaming',
        //                    'short_name' => 'BG',
        //                    'order' => 10,
        //                    'status' => 1,
        //                ],
        //                [
        //                    'code' => '1006',
        //                    'name' => 'Pragmatic Play',
        //                    'short_name' => 'PP',
        //                    'order' => 1,
        //                    'status' => 1,
        //                ],
           
        //                [
        //                    'code' => '1009',
        //                    'name' => 'CQ9',
        //                    'short_name' => 'CQ9',
        //                    'order' => 8,
        //                    'status' => 1,
        //                ],
        //                [
        //                    'code' => '1013',
        //                    'name' => 'Joker',
        //                    'short_name' => 'Joker',
        //                    'order' => 12,
        //                    'status' => 1,
        //                ],
        //                [
        //                    'code' => '1022',
        //                    'name' => 'Sexy Gaming',
        //                    'short_name' => 'SexyGaming',
        //                    'order' => 38,
        //                    'status' => 1,
        //                ],
        //                [
        //                    'code' => '1041',
        //                    'name' => 'Habanero',
        //                    'short_name' => 'Habanero',
        //                    'order' => 41,
        //                    'status' => 1,
        //                ],
        //                 [
        //                    'code' => '1050',
        //                    'name' => 'PlayStar',
        //                    'short_name' => 'PlayStar',
        //                    'order' => 6,
        //                    'status' => 1,
        //                ],
        //                  [
        //                    'code' => '1077',
        //                    'name' => 'Skywind',
        //                    'short_name' => 'SW',
        //                    'order' => 29,
        //                    'status' => 1,
        //                ],
        //                [
        //                    'code' => '1084',
        //                    'name' => 'Advant Play',
        //                    'short_name' => 'AP',
        //                    'order' => 45,
        //                    'status' => 1,
        //                ],
        //                    [
        //                    'code' => '1085',
        //                    'name' => 'JDB',
        //                    'short_name' => 'JDB',
        //                    'order' => 4,
        //                    'status' => 1,
        //                ],
        //                 [
        //                    'code' => '1091',
        //                    'name' => 'Jili',
        //                    'short_name' => 'JILI',
        //                    'order' => 3,
        //                    'status' => 1,
        //                ],
        //            ];

        //Product::insert($data);
        $data=[
            [
                'code' => '1009',
                'name' => 'CQ9',
                'short_name' => 'CQ9',
                'order' => 1,
                'status' => 1,
            ],
            [
                'code' => '1020',
                'name' => 'WM Casino',
                'short_name' => 'WM',
                'order' => 2,
                'status' => 1,
            ],
            [
                'code' => '1022',
                'name' => 'Sexy_gaming',
                'short_name' => 'SEXY_GAMING',
                'order' => 3,
                'status' => 1,
            ],
            [
                'code' => '1033',
                'name' => 'SV388cockfighting',
                'short_name' => 'SV388COCKFIGHTING',
                'order' => 4,
                'status' => 1,
            ],
            [
                'code' => '1050',
                'name' => 'PlayStar',
                'short_name' => 'PLAYSTAR',
                'order' => 5,
                'status' => 1,
            ],
            [
                'code' => '1055',
                'name' => 'MrSlotty',
                'short_name' => 'MRSLOTTY',
                'order' => 6,
                'status' => 1,
            ],
            [
                'code' => '1056',
                'name' => 'TrueLab',
                'short_name' => 'TRUELAB',
                'order' => 7,
                'status' => 1,
            ],
            [
                'code' => '1058',
                'name' => 'BGaming',
                'short_name' => 'BGAMING',
                'order' => 8,
                'status' => 1,
            ],
            [
                'code' => '1060',
                'name' => 'Volt Entertainment',
                'short_name' => 'VOLT',
                'order' => 9,
                'status' => 1,
            ],
            [
                'code' => '1062',
                'name' => 'Fazi',
                'short_name' => 'FAZI',
                'order' => 10,
                'status' => 1,
            ],
            [
                'code' => '1064',
                'name' => 'Netgame',
                'short_name' => 'NETGAME',
                'order' => 11,
                'status' => 1,
            ],
            [
                'code' => '1065',
                'name' => 'Kiron',
                'short_name' => 'KIRON',
                'order' => 12,
                'status' => 1,
            ],
            [
                'code' => '1067',
                'name' => 'RedRake',
                'short_name' => 'REDRAKE',
                'order' => 13,
                'status' => 1,
            ],
            [
                'code' => '1070',
                'name' => 'Booongo',
                'short_name' => 'BOOONGO',
                'order' => 14,
                'status' => 1,
            ],
            [
                'code' => '1080',
                'name' => 'Venus',
                'short_name' => 'VENUS',
                'order' => 15,
                'status' => 1,
            ],
            [
                'code' => '1097',
                'name' => 'FuntaGaming',
                'short_name' => 'FUNTAGAMING',
                'order' => 16,
                'status' => 1,
            ],
            [
                'code' => '1098',
                'name' => 'Felix',
                'short_name' => 'FELIX',
                'order' => 17,
                'status' => 1,
            ],
            [
                'code' => '1111',
                'name' => 'GamingWorld',
                'short_name' => 'GAMINGWORLD',
                'order' => 18,
                'status' => 1,
            ],
            [
                'code' => '1101',
                'name' => 'ZeusPlay',
                'short_name' => 'ZEUSPLAY',
                'order' => 19,
                'status' => 1,
            ],
            [
                'code' => '1102',
                'name' => 'KAGaming',
                'short_name' => 'KAGAMING',
                'order' => 20,
                'status' => 1,
            ],
            [
                'code' => '1138',
                'name' => 'Spribe',
                'short_name' => 'SPRIBE',
                'order' => 21,
                'status' => 1,
            ],
            [
                'code' => '1139',
                'name' => 'Fastspin',
                'short_name' => 'FASTSPIN',
                'order' => 22,
                'status' => 1,
            ],
            [
                'code' => '1149',
                'name' => 'AI Live Casino',
                'short_name' => 'AI',
                'order' => 23,
                'status' => 1,
            ],
            [
                'code' => '1148',
                'name' => 'WOW Gaming',
                'short_name' => 'WOW',
                'order' => 24,
                'status' => 1,
            ],
            [
                'code' => '1006',
                'name' => 'Pragmatic Play',
                'short_name' => 'PG',
                'order' => 25,
                'status' => 1,
            ],
            [
                'code' => '1011',
                'name' => 'Play Tech',
                'short_name' => 'PLAY',
                'order' => 26,
                'status' => 1,
            ],
            [
                'code' => '1016',
                'name' => 'YeeBet',
                'short_name' => 'YEEBET',
                'order' => 27,
                'status' => 1,
            ],
            [
                'code' => '1091',
                'name' => 'Jili tcg',
                'short_name' => 'JILI',
                'order' => 28,
                'status' => 1,
            ],
            [
                'code' => '1018',
                'name' => 'live_22',
                'short_name' => 'LIVE_22',
                'order' => 29,
                'status' => 1,
            ],
            [
                'code' => '1012',
                'name' => 'SBO',
                'short_name' => 'SBO',
                'order' => 30,
                'status' => 1,
            ],
            [
                'code' => '1052',
                'name' => 'DreamGaming',
                'short_name' => 'DREAMGAMING',
                'order' => 31,
                'status' => 1,
            ],
            [
                'code' => '1085',
                'name' => 'JDB',
                'short_name' => 'JDB',
                'order' => 32,
                'status' => 1,
            ],
            [
                'code' => '1049',
                'name' => 'Evoplay',
                'short_name' => 'EVOPLAY',
                'order' => 33,
                'status' => 1,
            ],
            [
                'code' => '1153',
                'name' => 'Hacksaw',
                'short_name' => 'HACKSAW',
                'order' => 34,
                'status' => 1,
            ],
            [
                'code' => '1154',
                'name' => 'Bigpot',
                'short_name' => 'BIGPOT',
                'order' => 35,
                'status' => 1,
            ],
            [
                'code' => '1157',
                'name' => 'IMoon',
                'short_name' => 'IMOON',
                'order' => 36,
                'status' => 1,
            ],
            [
                'code' => '1161',
                'name' => 'TADA',
                'short_name' => 'TADA',
                'order' => 37,
                'status' => 1,
            ],
            [
                'code' => '1166',
                'name' => 'NO LIMIT CITY (ASIA)',
                'short_name' => 'NO',
                'order' => 38,
                'status' => 1,
            ],
            [
                'code' => '1167',
                'name' => 'BIG TIME GAMING (ASIA)',
                'short_name' => 'BIG',
                'order' => 39,
                'status' => 1,
            ],
            [
                'code' => '1172',
                'name' => 'WORLD ENTERTAINMENT',
                'short_name' => 'WORLD',
                'order' => 40,
                'status' => 1,
            ],
            [
                'code' => '1183',
                'name' => 'FB SPORT',
                'short_name' => 'FB',
                'order' => 41,
                'status' => 1,
            ],
            [
                'code' => '11521',
                'name' => 'XBET',
                'short_name' => 'XBET',
                'order' => 42,
                'status' => 1,
            ],
            [
                'code' => '1168',
                'name' => 'Netent（ASIA）',
                'short_name' => 'NETENT（ASIA）',
                'order' => 43,
                'status' => 1,
            ],
            [
                'code' => '1169',
                'name' => 'Red Tiger（ASIA）',
                'short_name' => 'RED',
                'order' => 44,
                'status' => 1,
            ],
            [
                'code' => '1040',
                'name' => 'WBET',
                'short_name' => 'WBET',
                'order' => 45,
                'status' => 1,
            ],
            [
                'code' => '1184',
                'name' => 'RICH88',
                'short_name' => 'RICH88',
                'order' => 46,
                'status' => 1,
            ],
            [
                'code' => '1079',
                'name' => 'Fachai',
                'short_name' => 'FACHAI',
                'order' => 47,
                'status' => 1,
            ],
            [
                'code' => '1046',
                'name' => 'IBC-SABA',
                'short_name' => 'IBC-SABA',
                'order' => 48,
                'status' => 1,
            ],
            [
                'code' => '1185',
                'name' => 'SA Gaming',
                'short_name' => 'SA',
                'order' => 49,
                'status' => 1,
            ],
            [
                'code' => '1002',
                'name' => 'Evolution Gaming（ASIA）',
                'short_name' => 'EVOLUTION',
                'order' => 50,
                'status' => 1,
            ],
            [
                'code' => '1038',
                'name' => 'King855/CT855',
                'short_name' => 'KING855/CT855',
                'order' => 51,
                'status' => 1,
            ],
            [
                'code' => '1191',
                'name' => 'King855/CT855',
                'short_name' => 'KING855/CT855',
                'order' => 52,
                'status' => 1,
            ],
            [
                'code' => '1007',
                'name' => 'PG Soft',
                'short_name' => 'PG',
                'order' => 53,
                'status' => 1,
            ],
            [
                'code' => '1156',
                'name' => 'Betfair',
                'short_name' => 'BETFAIR',
                'order' => 54,
                'status' => 1,
            ],
            [
                'code' => '1158',
                'name' => 'Pascal Gaming',
                'short_name' => 'PASCAL',
                'order' => 55,
                'status' => 1,
            ],
            [
                'code' => '1004',
                'name' => 'BigGaming',
                'short_name' => 'BIGGAMING',
                'order' => 56,
                'status' => 1,
            ],
            [
                'code' => '1160',
                'name' => 'EPICWIN',
                'short_name' => 'EPICWIN',
                'order' => 57,
                'status' => 1,
            ],
            [
                'code' => '1163',
                'name' => 'NOVOMATIC',
                'short_name' => 'NOVOMATIC',
                'order' => 58,
                'status' => 1,
            ],
            [
                'code' => '1162',
                'name' => 'Octoplay',
                'short_name' => 'OCTOPLAY',
                'order' => 59,
                'status' => 1,
            ],
            [
                'code' => '1165',
                'name' => 'aviatrix',
                'short_name' => 'AVIATRIX',
                'order' => 60,
                'status' => 1,
            ],
            [
                'code' => '1164',
                'name' => 'DIGITAIN',
                'short_name' => 'DIGITAIN',
                'order' => 61,
                'status' => 1,
            ],
            [
                'code' => '1170',
                'name' => 'smartsoft',
                'short_name' => 'SMARTSOFT',
                'order' => 62,
                'status' => 1,
            ],
            [
                'code' => '1171',
                'name' => 'FIABLE GAMES',
                'short_name' => 'FIABLE',
                'order' => 63,
                'status' => 1,
            ],
            [
                'code' => '1173',
                'name' => 'Evolution (LATAM)',
                'short_name' => 'EVOLUTION',
                'order' => 64,
                'status' => 1,
            ],
            [
                'code' => '1174',
                'name' => 'Netent (LATAM)',
                'short_name' => 'NETENT',
                'order' => 65,
                'status' => 1,
            ],
            [
                'code' => '1175',
                'name' => 'Red Tiger (LATAM)',
                'short_name' => 'RED',
                'order' => 66,
                'status' => 1,
            ],
            [
                'code' => '1176',
                'name' => 'no limit city (LATAM)',
                'short_name' => 'NO',
                'order' => 67,
                'status' => 1,
            ],
            [
                'code' => '1177',
                'name' => 'big time gaming(LATAM)',
                'short_name' => 'BIG',
                'order' => 68,
                'status' => 1,
            ],
            [
                'code' => '1115',
                'name' => 'BOOMING GAMES',
                'short_name' => 'BOOMING',
                'order' => 69,
                'status' => 1,
            ],
            [
                'code' => '1186',
                'name' => 'ENDORPHINA',
                'short_name' => 'ENDORPHINA',
                'order' => 70,
                'status' => 1,
            ],
            [
                'code' => '1187',
                'name' => 'WINFINITY',
                'short_name' => 'WINFINITY',
                'order' => 71,
                'status' => 1,
            ],
            [
                'code' => '1192',
                'name' => 'AMIGO GAMING',
                'short_name' => 'AMIGO',
                'order' => 72,
                'status' => 1,
            ],
            [
                'code' => '1193',
                'name' => 'FB Games',
                'short_name' => 'FB',
                'order' => 73,
                'status' => 1,
            ],
            [
                'code' => '1197',
                'name' => 'Habanero',
                'short_name' => 'HABANERO',
                'order' => 74,
                'status' => 1,
            ],
            [
                'code' => '1194',
                'name' => 'PRETTY GAMING',
                'short_name' => 'PRETTY',
                'order' => 75,
                'status' => 1,
            ],
            [
                'code' => '1203',
                'name' => 'PlayAce',
                'short_name' => 'PLAYACE',
                'order' => 76,
                'status' => 1,
            ],
            [
                'code' => '1221',
                'name' => 'SPADE GAMING',
                'short_name' => 'SPADE',
                'order' => 77,
                'status' => 1,
            ],
            [
                'code' => '1204',
                'name' => 'ADVANTPLAY',
                'short_name' => 'ADVANTPLAY',
                'order' => 78,
                'status' => 1,
            ],
            [
                'code' => '1222',
                'name' => 'TF Gaming',
                'short_name' => 'TF',
                'order' => 79,
                'status' => 1,
            ],
            [
                'code' => '1220',
                'name' => 'ASTAR',
                'short_name' => 'ASTAR',
                'order' => 80,
                'status' => 1,
            ],
            [
                'code' => '1205',
                'name' => 'AMBPOKER',
                'short_name' => 'AMBPOKER',
                'order' => 81,
                'status' => 1,
            ],
            [
                'code' => '1206',
                'name' => 'SlotXO(AMB)',
                'short_name' => 'SLOTXOAMB',
                'order' => 82,
                'status' => 1,
            ],
            [
                'code' => '1207',
                'name' => 'PG SOFT (AMB)',
                'short_name' => 'PG',
                'order' => 83,
                'status' => 1,
            ],
            [
                'code' => '1225',
                'name' => 'JOKER',
                'short_name' => 'JOKER',
                'order' => 84,
                'status' => 1,
            ],
            [
                'code' => '1229',
                'name' => 'PANDA SPORTS',
                'short_name' => 'PANDA',
                'order' => 85,
                'status' => 1,
            ],
            [
                'code' => '1223',
                'name' => 'ALLBET',
                'short_name' => 'ALLBET',
                'order' => 86,
                'status' => 1,
            ],
            [
                'code' => '1224',
                'name' => 'GEMINI',
                'short_name' => 'GEMINI',
                'order' => 87,
                'status' => 1,
            ]
        ];
        foreach ($data as $obj) {
            Product::create($obj);
        }

    }
}
